# Generated by Django 5.1.6 on 2025-05-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_payment_method_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt khi nhận hàng'), ('online', 'Thanh toán online')], max_length=100, null=True),
        ),
    ]
