# Generated by Django 5.1.6 on 2025-05-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress',
            new_name='address',
        ),
    ]
