# Generated by Django 5.1.6 on 2025-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_adress_shippingadress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
